### ISSUE TITLE
Fix support for content on RSS feeds

### ISSUE THREAD

**Issue by zaosoula** [Guichaguri/post-feed-reader#3]
I found some inconsistencies, while parsing a RSS feed the ``content`` property of a post will contains its ``<description>`` instead of the actual content.
[source](https://github.com/Guichaguri/post-feed-reader/blob/main/src/feed/parseRssFeed.ts#L69-L71)

Here is my proposal: 
```ts
interface PostItem {
   ...
  /**
   * The item content
   *
   * `content` from Atom 1.0 and WP API
   * `content` from RSS 0.91, RSS 1.0 and RSS 2.0
   * `content_html` and `content_text` from JSON Feed 1.1
   */
  content?: PostContent;

  /**
   * The item summary or excerpt
   *
   * `summary` from Atom 1.0 and JSON Feed 1.1
   * `description` from RSS 0.91, RSS 1.0 and RSS 2.0
   * `excerpt` from WP API
   */
  summary?: PostContent;
   ...
}
```

**Comment by Guichaguri** [comment]
Thanks for reporting the issue! Do you have an example of the RSS feed that is not being parsed properly?
